# Generated by Django 5.1.7 on 2025-04-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_scoreentry_fairway_hit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreentry',
            old_name='fairway_hit',
            new_name='fairways_hit',
        ),
        migrations.RemoveField(
            model_name='scoreentry',
            name='date_played',
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='hole_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='putts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='strokes',
            field=models.IntegerField(),
        ),
    ]
